export const twelveItemBoxShopifyProductID = '1264075';
export const twelveItemBoxShopifyVariantID = '29641298968675';
export const twentyFourItemBoxShopifyProductID = '1264076';
export const twentyFourItemBoxShopifyVariantID = '29630825529443';
export const PRODUCT_ID = {
  12: twelveItemBoxShopifyProductID,
  24: twentyFourItemBoxShopifyProductID,
};
export const VARIANT_ID = {
  12: twelveItemBoxShopifyVariantID,
  24: twentyFourItemBoxShopifyVariantID,
};
export const PRICING = {
  12: '5.49',
  24: '4.69',
};

export const PRODUCT_RECOMMENDATIONS = {
  1286397: {id: 1286397, quantity: {12: 1, 24: 2}, title: 'Apple π Oatmeal'},
  1286393: {id: 1286393, quantity: {12: 2, 24: 3}, title: 'Baby Burrito Bowl'},
  1286392: {id: 1286392, quantity: {12: 2, 24: 4}, title: 'Bananas Foster'},
  1286399: {id: 1286399, quantity: {12: 2, 24: 4}, title: 'Coconut Curry'},
  1286395: {id: 1286395, quantity: {12: 1, 24: 2}, title: 'I Think Therefore I Yam'},
  1335664: {id: 1335664, quantity: {12: 1, 24: 3}, title: 'Fill Me Up Butternut'},
  1286398: {id: 1286398, quantity: {12: 1, 24: 2}, title: 'The Perks of Being A Cauliflower'},
  1286394: {id: 1286394, quantity: {12: 1, 24: 2}, title: 'The Wizard of Orzo'},
  1286391: {id: 1286391, quantity: {12: 1, 24: 2}, title: 'Valencian Paella'},
};

export const FAMILY_TIME_VARIANT_ID = '28208433758307';
export const FAMILY_TIME_PRODUCT_ID = '3563244126307';
export const FAMILY_TIME_PRICE = '14.99';

// tslint:disable-next-line
export const states_hash = {
  'Alabama': 'AL',
  'Arizona': 'AZ',
  'Arkansas': 'AR',
  'California': 'CA',
  'Colorado': 'CO',
  'Connecticut': 'CT',
  'Delaware': 'DE',
  'District Of Columbia': 'DC',
  'Florida': 'FL',
  'Georgia': 'GA',
  'Idaho': 'ID',
  'Illinois': 'IL',
  'Indiana': 'IN',
  'Iowa': 'IA',
  'Kansas': 'KS',
  'Kentucky': 'KY',
  'Louisiana': 'LA',
  'Maine': 'ME',
  'Maryland': 'MD',
  'Massachusetts': 'MA',
  'Michigan': 'MI',
  'Minnesota': 'MN',
  'Mississippi': 'MS',
  'Missouri': 'MO',
  'Montana': 'MT',
  'Nebraska': 'NE',
  'Nevada': 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Ohio': 'OH',
  'Oklahoma': 'OK',
  'Oregon': 'OR',
  'Pennsylvania': 'PA',
  'Puerto Rico': 'PR',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  'Tennessee': 'TN',
  'Texas': 'TX',
  'Utah': 'UT',
  'Vermont': 'VT',
  'Virginia': 'VA',
  'Washington': 'WA',
  'West Virginia': 'WV',
  'Wisconsin': 'WI',
  'Wyoming': 'WY',
};

export const stateOptions = [
  { name: 'Alabama', value: 'Alabama' },
  { name: 'Arizona', value: 'Arizona' },
  { name: 'Arkansas', value: 'Arkansas' },
  { name: 'California', value: 'California' },
  { name: 'Colorado', value: 'Colorado' },
  { name: 'Connecticut', value: 'Connecticut' },
  { name: 'Delaware', value: 'Delaware' },
  { name: 'District Of Columbia', value: 'District Of Columbia' },
  { name: 'Florida', value: 'Florida' },
  { name: 'Georgia', value: 'Georgia' },
  { name: 'Idaho', value: 'Idaho' },
  { name: 'Illinois', value: 'Illinois' },
  { name: 'Indiana', value: 'Indiana' },
  { name: 'Iowa', value: 'Iowa' },
  { name: 'Kansas', value: 'Kansas' },
  { name: 'Kentucky', value: 'Kentucky' },
  { name: 'Louisiana', value: 'Louisiana' },
  { name: 'Maine', value: 'Maine' },
  { name: 'Maryland', value: 'Maryland' },
  { name: 'Massachusetts', value: 'Massachusetts' },
  { name: 'Michigan', value: 'Michigan' },
  { name: 'Minnesota', value: 'Minnesota' },
  { name: 'Mississippi', value: 'Mississippi' },
  { name: 'Missouri', value: 'Missouri' },
  { name: 'Montana', value: 'Montana' },
  { name: 'Nebraska', value: 'Nebraska' },
  { name: 'Nevada', value: 'Nevada' },
  { name: 'New Hampshire', value: 'New Hampshire' },
  { name: 'New Jersey', value: 'New Jersey' },
  { name: 'New Mexico', value: 'New Mexico' },
  { name: 'New York', value: 'New York' },
  { name: 'North Carolina', value: 'North Carolina' },
  { name: 'North Dakota', value: 'North Dakota' },
  { name: 'Ohio', value: 'Ohio' },
  { name: 'Oklahoma', value: 'Oklahoma' },
  { name: 'Oregon', value: 'Oregon' },
  { name: 'Pennsylvania', value: 'Pennsylvania' },
  { name: 'Rhode Island', value: 'Rhode Island' },
  { name: 'South Carolina', value: 'South Carolina' },
  { name: 'South Dakota', value: 'South Dakota' },
  { name: 'Tennessee', value: 'Tennessee' },
  { name: 'Texas', value: 'Texas' },
  { name: 'Utah', value: 'Utah' },
  { name: 'Vermont', value: 'Vermont' },
  { name: 'Virginia', value: 'Virginia' },
  { name: 'Washington', value: 'Washington' },
  { name: 'West Virginia', value: 'West Virginia' },
  { name: 'Wisconsin', value: 'Wisconsin' },
  { name: 'Wyoming', value: 'Wyoming' },
];
